### ISSUE TITLE
Different output from Release mode and Debug mode

### ISSUE THREAD

**Issue by shanchao95** [alecjacobson/computer-graphics-ray-tracing#11]
hi, I tried both release mode and debug mode, but they gave me a different output.

**Comment by shanchao95** [comment]
I found the default initialization value of Eigen::Vector3 are different in Release and Debug mode.  (1,1,1) for Release and (0,0,0) for Debug.

**Comment by alecjacobson** [comment]
It's unlikely that Eigen::Vector3d is actually initialized to (1,1,1) in
Release mode. I'm guessing that just happens to be what was in memory.

I.e., don't count on it being (1,1,1) without setting it to that.

Similarly, in debug mode, I think windows sets arrays by default to 0,0,0
but that will not be guaranteed everywhere.

>

**Comment by shanchao95** [comment]
thanks!
