### ISSUE TITLE
Directional Light - 2 variables with the same name?

### ISSUE THREAD

**Issue by JPrier** [alecjacobson/computer-graphics-ray-tracing#13]
In DirectionLight we are supposed to find the d vector (direction from point toward light) but the DirectionalLight class also has a d vector (direction from light toward scene) which is different. Am I missing something in order to differ between these variables?

**Comment by RioAraki** [comment]
Hey I also have the same confusion, have you found the answer to this question?

**Comment by DavidCollard** [comment]
https://www.javatpoint.com/cpp-this-pointer
