### ISSUE TITLE
Image file will not appear

### ISSUE THREAD

**Issue by Xeroken** [alecjacobson/computer-graphics-ray-tracing#17]
I don't know if it has something to do with the six files I edited for the assignment, but when I compile it and run ./raytracing, no image is outputted. I checked main.cpp and it should take the sphere and plane data and output rgb.ppm. Also, no error messages pop up during compiling or execution.

**Comment by alecjacobson** [comment]
guessing this is an issue with the `write_ppm.cpp` implementation.
