### ISSUE TITLE
Submitting a stl for creative.json

### ISSUE THREAD

**Issue by mShulman2015** [alecjacobson/computer-graphics-ray-tracing#18]
Is it possible to submit an .stl for the creative.json, I  was under the impression we were allowed to use anything we wanted for the triangle soup. So I used a small (2MB) stl file from the internet.  But the problem is MarkUs doesn't let me upload any files other than the ones specified in the input.

Is there a way to modify the MarkUs submission requirements, or maybe give us a place to email them?

**Comment by psarahdactyl** [comment]
Thanks! Fixed. You should be able to submit stl files now.
