### ISSUE TITLE
How to get light source in PointLight?

### ISSUE THREAD

**Issue by RioAraki** [alecjacobson/computer-graphics-ray-tracing#7]
I am a bit confused about the PointLight.cpp. It gives a query point (the hit point?) and asks for the direction and parametric distance, why the light source is not given in the parameter so we can make the subtraction?

I could see from `read_json`, `parse_lights` function actually  calls the `PointLight()` first, then set the attribute p for position and I for intensity and finally push it back to the lights array. Shouldn't the right order be parsing the position first, pass it into `PointLight()` to do the calculation about direction, then push back to the light array? May anyone explains why its been written like this? Did I understand anything wrong?

**Comment by DavidCollard** [comment]
parse_lights should have nothing to do with your implementation of PointLight::direction. parse_lights only sets the members of those light objects, it does nothing actually related to the functionality of it.

PointLight::direction takes as input a point to query, and returns via reference a direction (from query point to light point) and the parameter. See PointLight.h and Light.h for more details in that regard. There's nothing particularly special going on here, just basic inheritance and returning values by reference like the last two assignments.

**Comment by RioAraki** [comment]
To make it clear and answer my question, I didn't see there is a variable `p` stands for position lying there in `pointlight.h`. That's stupid.
